#!/usr/bin/env node
'use strict';

const crypto = require('crypto');
const fs = require('fs');
const path = require('path');

const HERE = __dirname;
const ROOT = path.join(HERE, '..', '..');
const SOURCE = path.join(ROOT, 'src', 'assets', 'map-contours.json');
const OUTPUT = path.join(HERE, 'generated', 'map-contours.js');

const sourceText = fs.readFileSync(SOURCE, 'utf8');
const contours = JSON.parse(sourceText);
const sourceSha = crypto.createHash('sha256').update(sourceText).digest('hex');
const generated = [
  '/* Generated by build-data.js from src/assets/map-contours.json.',
  '   Source SHA-256: ' + sourceSha,
  '   Do not edit this file by hand. */',
  '(function (root) {',
  "  'use strict';",
  '  root.SkipiShippingGameBundledContours = ' + JSON.stringify(contours) + ';',
  "})(typeof globalThis !== 'undefined' ? globalThis : this);",
  ''
].join('\n');

fs.mkdirSync(path.dirname(OUTPUT), { recursive: true });
if (!fs.existsSync(OUTPUT) || fs.readFileSync(OUTPUT, 'utf8') !== generated) {
  fs.writeFileSync(OUTPUT, generated);
  console.log('generated ' + path.relative(ROOT, OUTPUT) + ' from bundled contours');
} else {
  console.log('generated contours already current');
}
